name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  preflight:
    runs-on: ubuntu-latest

    # Skip the entire job for draft PRs
    if: github.event.pull_request.draft == false

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-24.11
          extra_nix_config: |
            extra-platforms = aarch64-linux

      - name: Unit Tests
        run: nix develop --command zig build test
